FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dev
WORKDIR /app

# Copia os arquivos da aplicação para dentro do container
COPY src/ ./src/

WORKDIR /app/src/Ryze.Web

# Restaura dependências
RUN dotnet restore

# Instala o dotnet-watch (se necessário)
# RUN dotnet tool install --global dotnet-watch

EXPOSE 80

# Usa o dotnet watch para desenvolvimento com hot reload
ENTRYPOINT ["dotnet", "watch", "--no-hot-reload", "run", "--urls=http://0.0.0.0:80"]