# Etapa 1: imagem com SDK
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dev
WORKDIR /app

# Copia tudo para dentro do container
COPY src/ ./src/
WORKDIR /app/src/Ryze.Web

# Ferramentas úteis
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

# Restaura dependências
RUN dotnet restore

# Inicia com watch
CMD ["dotnet", "watch", "--no-hot-reload", "--project", "/app/src/Ryze.Web", "run", "--urls=http://0.0.0.0:80"]